apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: l9bdxpkrp-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-nodejs:19f34bb35b0d3755eb91af522aa62148403fb3a5@sha256:f569ebf56b8a00d963d0a0c3085ce66f6a23a5fb2903d79fe10894bc3fb36b98
          name: container-image
